name: Branch developer test

on:
  push:
    branches: developer

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

      if: failure()
      - name: Reset para o últmo commit
      with:
        run: git reset --hard HEAD~1

        - name: Rebuild na versão anterior
        run: mvn -B package --file pom.xml

    - name: Send mail
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
    # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
      # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
      # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
      # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
      # comma-separated string, send email to
        to: luiseduardo20.dev@gmail.com, spfcarthur1@gmail.com, dsilverfox98@gmail.com
      # from email name
        from: Loteria UPE